import { Footer } from "@/components/footer/layout"
import { Header } from "@/components/header/layout"
import '../global.css';

export const metadata = {
  title: 'Next Pract',
  description: 'Generated by Next.js'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex flex-col m-auto items-center h-full justify-center bg-slate-200">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
